name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          # Will assume basic setup has been done on the server
          script: |
            exit 1
            cd excalihub || exit 1
            git pull || exit 1
            export NVM_DIR=~/.nvm || exit 1
            source ~/.nvm/nvm.sh || exit 1
            pm2 stop all || exit 1
            npm i || exit 1
            npm run build || exit 1
            pm2 restart all || exit 1
            pm2 save || exit 1
            exit 0