name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          # Will assume basic setup has been done on the server
          script: |
            cd excalihub
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm i
            npm run build
            pm2 restart all
            pm2 save
            exit